name: Setup
description: Install dependencies and build

runs:
  using: 'composite'
  steps:
    - name: Use Node.js v16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Cache node_modules
      uses: actions/cache@v2
      id: node_modules-cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: publish-${{ runner.os }}-node_modules-cache-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          publish-${{ runner.os }}-node_modules-cache-
    - name: Install dependencies
      run: |
        make dep
      shell: bash
