name: Blockchain
title: Blockchain
description: Website and Documentation for ArcBlock Blockchain
github: https://github.com/arcblock/blockchain-site
theme: arcblock
themeConfig:
  colors:
    primary: '#1DC1C7'
